apiVersion: v1
kind: Service
metadata:
  name: jenkins-masters
  namespace: jenkins
  annotations: 
     metallb.universe.tf/address-pool: production-public-ips
spec:
  type: LoadBalancer
  ports:
    - port: 50000
      targetPort: 50000
      name: jenkins-jnlp
    - port: 80
      targetPort: 8080
      name: jenkins-master  
  selector:
    app: jenkins-master
