apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: jenkins-master
  externalIPs:
    - 192.168.1.161  
  selector:
    app: jenkins-master
