apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-volume
  namespace: sonar
  labels:
    type: local
    name: sonar
spec:
  storageClassName: standart
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/sonarqube/data"

