apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pv-claim
  namespace: sonar
spec:
  storageClassName: standart
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
    
