apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alight-pv-claim
  namespace: alight
spec:
  storageClassName: standart
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    

