apiVersion: v1
kind: PersistentVolume
metadata:
  name: alight-pv-volume
  namespace: alight
  labels:
    type: local
    name: alight
spec:
  storageClassName: standart
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"

