apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: monitoring
spec:
  storageClassName: standart
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
