apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-back-vol
spec:
  storageClassName: standart
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: var/lib/etcd
